version: '3.1'

services:
  owncloud:
    #image: steven1991/owncloud:10.0.10
    image: steven1991/owncloud:15.0.14
#    container_name: owncloud-prod
    deploy:
      placement:
        constraints: [node.labels.cpu-type == x86]
    restart: always
    ports:
      - 443:443
    depends_on:
      - db
    volumes:
      - ./custom_apps:/var/www/html/custom_apps
      - ./apps:/var/www/html/apps
      - ./config:/var/www/html/config
#      - ./data:/var/www/html/data
      - /Data:/Data
      - ./certs:/etc/apache2/ssl
    networks:
      - owncloud-network

  db:
#    image: webhippie/mariadb:latest
    image: steven1991/mariadb:1.1
#    container_name: mariadb-prod
    deploy:
      placement:
        constraints: [node.labels.cpu-type == x86]
    restart: always
    environment:
     -  MARIADB_ROOT_PASSWORD=DOCKER_SECRET->oc_mysql_root
     -  MARIADB_USERNAME=root
     -  MARIADB_PASSWORD=DOCKER_SECRET->oc_mysql_root
     -  MARIADB_DATABASE=owncloud
     -  MARIADB_MAX_ALLOWED_PACKET=512M
     -  MARIADB_INNODB_LOG_FILE_SIZE=512M
     -  MARIADB_INNODB_LARGE_PREFIX=ON
     -  MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql
    secrets:
      - oc_mysql_root
    networks:
      - owncloud-network

secrets:
  oc_mysql_root:
    external: true  

networks:
  owncloud-network:
